Redo pr 17 and after
hiphops-io/hops pull request #19
Opened 2023-11-22 23:43 UTC by lukaso

Show event logs in UI

2023-11-22 23:59 UTC, lukaso commented on console/src/routes/advanced/+page.svelte
> +			<!--Tabs-->
Reason this is commented out is that the next story is to add this functionality in. Makes it (arguably) easier than stripping it out and then finding it again.

2023-11-23 09:17 UTC, lukaso commented
![](https://github.trello.services/images/mini-trello-icon.png) [[MVF:Medium] Hops users can see log of events](https://trello.com/c/SyP9xTso/1021-mvfmedium-hops-users-can-see-log-of-events)

2023-11-23 10:14 UTC, manterfield requested changes

2023-11-23 10:14 UTC, manterfield commented on nats/msgschema.go
> +		"notify",
Use the ChannelNotify const

2023-11-23 10:14 UTC, manterfield commented on nats/msgschema.go
> +		"event",
Create new const at top of file (similar to `HopsMessageId`, e.g. `SourceMessageId`)

2023-11-23 10:14 UTC, manterfield commented on nats/client.go
> +	msgs, _ := cons.FetchNoWait(1000000)
Change as discussed

2023-11-23 19:38 UTC, lukaso commented on internal/httpserver/eventrouter.go
> +func eventLogFromMsgMetas(msgs []*nats.MsgMeta, start time.Time) (*EventLog, error) {
```suggestion
// eventLogFromMsgMetas converst event messasges to the /events api, returning only the last 100 
func eventLogFromMsgMetas(msgs []*nats.MsgMeta, start time.Time) (*EventLog, error) {
```

2023-11-24 17:01 UTC, closed without merging